spring:
  datasource:
    url: jdbc:mysql://localhost:3306/School
    username: root
    password: Nebal077@@@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 6031
